name: "Generate GeoIP NFTables Map from MaxMind GeoLite2 Database"

on:
  schedule:
    - cron: 1 0 * * 0/2
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Run geoip generator
        run: |
          go run main.go

      - name: Gzip nftables and generate sha256 hash
        run: |
          tar -czf geoip_by_country.tar.gz by_country/
          sha256sum geoip_by_country.tar.gz > geoip_by_country.tar.gz.sha256
          gzip -9 -k geoip_ipv4.nft
          gzip -9 -k geoip_ipv6.nft
          sha256sum geoip_ipv4.nft > geoip_ipv4.nft.sha256sum
          sha256sum geoip_ipv6.nft > geoip_ipv6.nft.sha256sum
          sha256sum geoip_ipv4.nft.gz > geoip_ipv4.nft.gz.sha256sum
          sha256sum geoip_ipv6.nft.gz > geoip_ipv6.nft.gz.sha256sum
          
      - name: Release to latest
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: latest
          files: |
            geoip_by_country.tar.gz
            geoip_by_country.tar.gz.sha256
            geoip_ipv4.nft
            geoip_ipv6.nft
            geoip_ipv4.nft.gz
            geoip_ipv6.nft.gz
            geoip_ipv4.nft.sha256sum
            geoip_ipv6.nft.sha256sum
            geoip_ipv4.nft.gz.sha256sum
            geoip_ipv6.nft.gz.sha256sum
